sonar.projectKey=brunobizarri-experian_construcao-pipelines
sonar.organization=brunobizarri-experian

sonar.sources=calculadora_web
sonar.tests=tests
sonar.exclusions=**/venv/**,**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.14