name: Pipeline Calculadora WEB

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  source:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build da imagem Docker
        run: |
          docker build -t calculadora-web .

      - name: Rodar container (ex: testes)
        run: |
          docker run --rm calculadora-web